[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
build_flags =
    -ffreestanding
    -fno-exceptions
    -fno-rtti
    -nostdlib
    -nostartfiles
    -Wl,-Tgame.ld
    -Wl,-e,game_entry
    -Wl,--gc-sections
    -Iinclude
