[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
build_flags =
    -ffreestanding
    -fno-exceptions
    -fno-rtti
    -nostdlib
    -nostartfiles
    -Wl,-T../../game/game.ld
    -Wl,-e,game_entry
    -Wl,--gc-sections
    -I../../game/include
